"""new iefields in user model

Revision ID: 34717245485e
Revises: 5de384e8a051
Create Date: 2022-11-09 14:39:29.905207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34717245485e'
down_revision = '5de384e8a051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
